FROM ubuntu:14.04

RUN apt-get update && \
    echo "y" | apt-get install bash \
        qemu-kvm \
        python gcc \
        make \
        python-dev \
        vim 

COPY psvmi psvmi
RUN (cd psvmi; python setup.py build && python setup.py install)

COPY maps maps
COPY offsets offsets

# TODO(ricarkol): move this away
ADD header.h .

COPY tests tests
